site_name: LPP

nav:
- 'Teoría':
   - 'Descripción de la asignatura': 'teoria/tema00-descripcion-asignatura/tema00-descripcion-asignatura.md'

theme:
    language: es
    name: 'material'
    palette:
        primary: 'Orange'
        accent: 'Deep Orange'
       
markdown_extensions:
    - admonition
    - codehilite(guess_lang=false):
        linenums: true
    - footnotes
    - meta
    - toc(permalink=true)

